#ifndef D3D11DEFAULTSHADERS_H_
#define D3D11DEFAULTSHADERS_H_
//------------------------------------------------------------------------------
/**
    Default shader variations for the Direct3D 11 rendersystem

    (C) 2016 Christian Bleicher
*/

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgram =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "};\n"
    "cbuffer DefaultConstantBuffer : register(b1)\n"
    "{\n"
    "    float1 uMod;\n"
    "    float1 vMod;\n"
    "    float1 uScale;\n"
    "    float1 vScale;\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float2 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "    float4 colour : COLOR;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = input.uv;\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "    output.colour = input.colour;\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    output = texture0.Sample(samplerLinear, float2(uScale * input.uv.x + uMod, vScale * input.uv.y + vMod));\n"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramFog =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "    matrix worldMatrix;\n"
    "};\n"
    "cbuffer DefaultConstantBuffer : register(b1)\n"
    "{\n"
    "    matrix viewMatrix;\n"
    "    float1 uMod;\n"
    "    float1 vMod;\n"
    "    float1 uScale;\n"
    "    float1 vScale;\n"
    "    int fogMode;\n"
    "    float1 fogStart;\n"
    "    float1 fogEnd;\n"
    "    float3 fogColour;\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float2 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "    float4 colour : COLOR;\n"
    "    float1 fogFactor : FOG;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = input.uv;\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "    output.colour = input.colour;\n"
    "    if (1 == fogMode)\n"
    "    {\n"
    "        // range based linear fog\n"
    "        output.fogFactor = clamp((fogEnd - length(mul(mul(float4(input.position, 1.0f), worldMatrix), viewMatrix))) / (fogEnd - fogStart), 0.0f, 1.0f);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        output.fogFactor = 1.0f;\n"
    "    }\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    output = lerp(float4(fogColour, 1.0f), texture0.Sample(samplerLinear, float2(uScale * input.uv.x + uMod, vScale * input.uv.y + vMod)), input.fogFactor.x);\n"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramLit =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "    matrix worldMatrix;\n"
    "};\n"
    "cbuffer DefaultConstantBuffer : register(b1)\n"
    "{\n"
    "    float1 uMod;\n"
    "    float1 vMod;\n"
    "    float1 uScale;\n"
    "    float1 vScale;\n"
    "    float3 cameraPosition;\n"
    "    matrix lightParams[4];\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float2 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "    float4 colour : COLOR;\n"
    "    float3 worldNormal : NORMAL;\n"
    "    float3 worldPosition : POSITION;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = input.uv;\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "    output.colour = input.colour;\n"
    "    output.worldNormal = normalize(mul(input.normal, float3x3(worldMatrix[0].xyz, worldMatrix[1].xyz, worldMatrix[2].xyz)));\n"
    "    output.worldPosition = mul(float4(input.position.xyz, 1.0f), worldMatrix).xyz;\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    float4 colour = texture0.Sample(samplerLinear, float2(uScale * input.uv.x + uMod, vScale * input.uv.y + vMod));\n"
    "    float3 L;\n"
    "    float3 diffuse = {0.0f, 0.0f, 0.0f};\n"
    "    float3 specular = {0.0f, 0.0f, 0.0f};\n"
    "    for (int i = 0; i < 4; ++i)\n"
    "    {\n"
    "        L = normalize(float3(lightParams[i][0][0], lightParams[i][1][0], lightParams[i][2][0]) - input.worldPosition);\n"
    "        diffuse += mul(float3(lightParams[i][0][1], lightParams[i][1][1], lightParams[i][2][1]), max(0.0f, dot(L, normalize(input.worldNormal))));\n"
    "        float specFactor = pow(max(0.0f, dot(reflect(-L, normalize(input.worldNormal)), normalize(cameraPosition - input.worldPosition))), lightParams[i][3][2]);\n"
    "        specular += mul(float3(lightParams[i][0][2], lightParams[i][1][2], lightParams[i][2][2]), specFactor);\n"
    "    }\n"
    "    colour.rgb = clamp(colour.rgb * (diffuse + specular), 0.0f, 1.0f);\n"
    "    output = colour;\n"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramLitFog =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "    matrix worldMatrix;\n"
    "};\n"
    "cbuffer DefaultConstantBuffer : register(b1)\n"
    "{\n"
    "    matrix viewMatrix;\n"
    "    float1 uMod;\n"
    "    float1 vMod;\n"
    "    float1 uScale;\n"
    "    float1 vScale;\n"
    "    int fogMode;\n"
    "    float1 fogStart;\n"
    "    float1 fogEnd;\n"
    "    float3 fogColour;\n"
    "    float3 cameraPosition;\n"
    "    matrix lightParams[4];\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float2 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "    float4 colour : COLOR;\n"
    "    float1 fogFactor : FOG;\n"
    "    float3 worldNormal : NORMAL;\n"
    "    float3 worldPosition : POSITION;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = input.uv;\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "    output.colour = input.colour;\n"
    "    if (1 == fogMode)\n"
    "    {\n"
    "        // range based linear fog\n"
    "        output.fogFactor = clamp((fogEnd - length(mul(mul(float4(input.position, 1.0f), worldMatrix), viewMatrix))) / (fogEnd - fogStart), 0.0f, 1.0f);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        output.fogFactor = 1.0f;\n"
    "    }\n"
    "    output.worldNormal = normalize(mul(input.normal, float3x3(worldMatrix[0].xyz, worldMatrix[1].xyz, worldMatrix[2].xyz)));\n"
    "    output.worldPosition = mul(float4(input.position.xyz, 1.0f), worldMatrix).xyz;\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    float4 colour = texture0.Sample(samplerLinear, float2(uScale * input.uv.x + uMod, vScale * input.uv.y + vMod));\n"
    "    float3 L;\n"
    "    float3 diffuse = {0.0f, 0.0f, 0.0f};\n"
    "    float3 specular = {0.0f, 0.0f, 0.0f};\n"
    "    for (int i = 0; i < 4; ++i)\n"
    "    {\n"
    "        L = normalize(float3(lightParams[i][0][0], lightParams[i][1][0], lightParams[i][2][0]) - input.worldPosition);\n"
    "        diffuse += mul(float3(lightParams[i][0][1], lightParams[i][1][1], lightParams[i][2][1]), max(0.0f, dot(L, normalize(input.worldNormal))));\n"
    "        float specFactor = pow(max(0.0f, dot(reflect(-L, normalize(input.worldNormal)), normalize(cameraPosition - input.worldPosition))), lightParams[i][3][2]);\n"
    "        specular += mul(float3(lightParams[i][0][2], lightParams[i][1][2], lightParams[i][2][2]), specFactor);\n"
    "    }\n"
    "    colour.rgb = clamp(colour.rgb * (diffuse + specular), 0.0f, 1.0f);\n"
    "    output = lerp(float4(fogColour, 1.0f), colour, input.fogFactor.x);\n"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramShadowCaster =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float4 position : SV_Position;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    output = float4(0.5, 0.5, 0.5, 1.0);\n"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramShadowReceiver =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "    matrix textureMatrix;\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float4 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = mul(float4(input.position, 1.0f), textureMatrix);\n"
    "    output.position = mul(float4(input.position, 1.0f), worldViewProjMatrix);\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    float4 colour = {1.0f, 1.0f, 1.0f, 1.0f};\n"
    "    if (input.uv.w > 0.0f)\n"
    "    {\n"
    "        colour = texture0.Sample(samplerLinear, input.uv.xy / input.uv.w);\n"
    "    }\n"
    "    output = colour;"
    "};\n";

//------------------------------------------------------------------------------
/**
*/
const char* const DefaultGpuProgramMorphAnim =
    "Texture2D texture0 : register(t0);\n"
    "SamplerState samplerLinear : register(s0);\n"
    "cbuffer AutoConstantBuffer : register(b0)\n"
    "{\n"
    "    matrix worldViewProjMatrix;\n"
    "    float1 morphWeight;\n"
    "};\n"
    "struct VertexIn\n"
    "{\n"
    "    float2 uv : TEXCOORD0;\n"
    "    float3 normal : NORMAL0;\n"
    "    float3 position : POSITION0;\n"
    "    float4 colour : COLOR0;\n"
    "    float2 uvTarget : TEXCOORD1;\n"
    "    float3 normalTarget : NORMAL1;\n"
    "    float3 positionMorphTarget : POSITION1;\n"
    "    float4 colourTarget : COLOR1;\n"
    "};\n"
    "struct VertexOut\n"
    "{\n"
    "    float2 uv : TEXCOORD;\n"
    "    float4 position : SV_Position;\n"
    "    float4 colour : COLOR;\n"
    "};\n"
    "void DefaultVertexShader(VertexIn input, out VertexOut output)\n"
    "{\n"
    "    output.uv = input.uv;\n"
    "    output.position = mul(float4((input.position + (input.positionMorphTarget - input.position) * morphWeight), 1.0f), worldViewProjMatrix);\n"
    "    output.colour = input.colour;\n"
    "}\n"
    "void DefaultFragmentShader(VertexOut input, out float4 output : SV_Target)\n"
    "{\n"
    "    output = texture0.Sample(samplerLinear, input.uv);\n"
    "};\n";
//------------------------------------------------------------------------------
#endif